<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class modelsPostProxy extends \models\Post implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->_load();
        return parent::setId($id);
    }

    public function setUser($user)
    {
        $this->_load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->_load();
        return parent::getUser();
    }

    public function setTitle($title)
    {
        $this->_load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->_load();
        return parent::getTitle();
    }

    public function setContent($content)
    {
        $this->_load();
        return parent::setContent($content);
    }

    public function getContent()
    {
        $this->_load();
        return parent::getContent();
    }

    public function setFlag($flag)
    {
        $this->_load();
        return parent::setFlag($flag);
    }

    public function getFlag()
    {
        $this->_load();
        return parent::getFlag();
    }

    public function setTags($tags)
    {
        $this->_load();
        return parent::setTags($tags);
    }

    public function getTags()
    {
        $this->_load();
        return parent::getTags();
    }

    public function setComments($comments)
    {
        $this->_load();
        return parent::setComments($comments);
    }

    public function getComments()
    {
        $this->_load();
        return parent::getComments();
    }

    public function setLikes($likes)
    {
        $this->_load();
        return parent::setLikes($likes);
    }

    public function getLikes()
    {
        $this->_load();
        return parent::getLikes();
    }

    public function setCreatedAt($created_at)
    {
        $this->_load();
        return parent::setCreatedAt($created_at);
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }

    public function setUpdatedAt($updated_at)
    {
        $this->_load();
        return parent::setUpdatedAt($updated_at);
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }

    public function getTagsNameArray()
    {
        $this->_load();
        return parent::getTagsNameArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'user', 'title', 'content', 'flag', 'tags', 'comments', 'likes', 'created_at', 'updated_at');
    }
}